import { supabase } from './supabase-config.js';

const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char]));
const formatMoney = (value) => Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const statusLabel = { disponivel: 'Disponível', poucas_unidades: 'Poucas unidades', esgotado: 'Esgotado', aguardando: 'Aguardando', em_andamento: 'Em andamento', realizado: 'Realizado', pendente: 'Pendente' };
let state = { produtos: [], sorteios: [], cronograma: [], alertChannel: null, alertStatus: 'CONECTANDO' };

function feedback(selector, message, isError = false) { const element = $(selector); element.textContent = message; element.classList.toggle('error', isError); }
function productControls(product) { return `<div class="status-controls"><button data-product-status="${product.id}|disponivel" class="${product.status === 'disponivel' ? 'selected' : ''}" type="button">Disponível</button><button data-product-status="${product.id}|poucas_unidades" class="${product.status === 'poucas_unidades' ? 'selected' : ''}" type="button">Poucas</button><button data-product-status="${product.id}|esgotado" class="${product.status === 'esgotado' ? 'selected' : ''}" type="button">Esgotado</button></div>`; }
function renderProducts() { $('#product-count').textContent = `${state.produtos.length} itens`; $('#admin-products').innerHTML = state.produtos.length ? state.produtos.map((product) => `<article class="admin-row"><div><h3>${escapeHtml(product.nome)}</h3><p>${formatMoney(product.preco)} · ${escapeHtml(product.categoria)}</p></div>${productControls(product)}</article>`).join('') : '<p class="muted">Nenhum item cadastrado.</p>'; }
function renderSelect() { const select = $('#active-draw'); const selected = select.value; select.innerHTML = state.sorteios.length ? state.sorteios.map((draw) => `<option value="${draw.id}">${escapeHtml(draw.identificacao)} — ${escapeHtml(draw.premio)}</option>`).join('') : '<option value="">Nenhum sorteio cadastrado</option>'; if (state.sorteios.some((draw) => String(draw.id) === selected)) select.value = selected; else { const active = state.sorteios.find((draw) => draw.status === 'em_andamento'); select.value = active?.id || state.sorteios[0]?.id || ''; } renderDrawConsole(); }
function renderDrawConsole() { const draw = state.sorteios.find((item) => String(item.id) === $('#active-draw').value); const consoleElement = $('#draw-console'); if (!draw) { consoleElement.innerHTML = '<p class="muted">Cadastre um sorteio no Supabase para controlá-lo aqui.</p>'; return; } const history = Array.isArray(draw.numeros_sorteados) ? draw.numeros_sorteados : []; consoleElement.innerHTML = `<div class="console-status"><span class="status status-${draw.status}">${statusLabel[draw.status]}</span><strong>${escapeHtml(draw.premio)}</strong><small>Último: ${draw.ultimo_numero ?? '—'} · Histórico: ${history.length}</small></div><div class="console-buttons"><button data-draw-status="em_andamento" type="button">Iniciar</button><button data-draw-status="aguardando" type="button">Pausar</button><button data-draw-status="realizado" type="button">Encerrar</button></div><form id="number-form" class="number-form"><label>Número chamado / lance<input id="called-number" inputmode="numeric" min="0" step="1" type="number" required /></label><button class="primary-button" type="submit">Confirmar</button></form><button id="reset-draw" class="danger-button" type="button">Limpar sorteio atual</button><p id="draw-feedback" class="feedback" role="status"></p>`; }
function renderSchedule() { $('#admin-schedule').innerHTML = state.cronograma.length ? state.cronograma.map((event) => `<article class="admin-row"><div><h3>${escapeHtml(event.evento)}</h3><p>${String(event.horario_previsto).slice(0, 5)} · ${statusLabel[event.status]}</p></div><button data-schedule-toggle="${event.id}|${event.status === 'realizado' ? 'pendente' : 'realizado'}" class="small-button" type="button">${event.status === 'realizado' ? 'Reverter' : 'Marcar realizado'}</button></article>`).join('') : '<p class="muted">Nenhum evento cadastrado.</p>'; }
function renderAll() { renderProducts(); renderSelect(); renderSchedule(); }
async function loadData() { const [produtos, sorteios, cronograma] = await Promise.all([supabase.from('produtos').select('*').order('nome'), supabase.from('sorteios').select('*').order('id', { ascending: false }), supabase.from('cronograma').select('*').order('horario_previsto')]); const error = [produtos, sorteios, cronograma].find((result) => result.error)?.error; if (error) { feedback('#login-feedback', error.message, true); return; } state.produtos = produtos.data || []; state.sorteios = sorteios.data || []; state.cronograma = cronograma.data || []; renderAll(); }
async function updateTable(table, values, id) { const { error } = await supabase.from(table).update(values).eq('id', id); if (error) throw error; }
async function subscribe() {
  ['produtos', 'sorteios', 'cronograma'].forEach((table) => supabase.channel(`admin-${table}`).on('postgres_changes', { event: '*', schema: 'public', table }, loadData).subscribe());
  // Canal privado: o Realtime valida as policies com o token da sessao do organizador.
  await supabase.realtime.setAuth();
  state.alertChannel = supabase.channel('avisos-globais', { config: { private: true } });
  state.alertStatus = 'CONECTANDO';
  state.alertChannel.subscribe((status, error) => { state.alertStatus = status; if (error) console.error('Canal de avisos:', error.message); });
}
async function showAdmin(session) { $('#login-panel').hidden = true; $('#admin-panel').hidden = false; $('#sign-out').hidden = false; $('#admin-email').textContent = session.user.email; await loadData(); await subscribe(); }

$('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); feedback('#login-feedback', 'Entrando...'); const { data, error } = await supabase.auth.signInWithPassword({ email: $('#email').value, password: $('#password').value }); if (error) { feedback('#login-feedback', error.message, true); return; } showAdmin(data.session); });
$('#sign-out').addEventListener('click', async () => { await supabase.auth.signOut(); window.location.reload(); });
$('#active-draw').addEventListener('change', renderDrawConsole);
document.addEventListener('click', async (event) => {
  const product = event.target.closest('[data-product-status]'); const drawStatus = event.target.closest('[data-draw-status]'); const schedule = event.target.closest('[data-schedule-toggle]');
  try {
    if (product) { const [id, status] = product.dataset.productStatus.split('|'); await updateTable('produtos', { status }, id); }
    if (drawStatus) { await updateTable('sorteios', { status: drawStatus.dataset.drawStatus }, $('#active-draw').value); feedback('#draw-feedback', 'Estado atualizado.'); }
    if (schedule) { const [id, status] = schedule.dataset.scheduleToggle.split('|'); await updateTable('cronograma', { status }, id); }
  } catch (error) { feedback('#draw-feedback', error.message, true); }
});
document.addEventListener('submit', async (event) => {
  if (event.target.id === 'number-form') { event.preventDefault(); const draw = state.sorteios.find((item) => String(item.id) === $('#active-draw').value); const number = Number($('#called-number').value); if (!Number.isInteger(number)) return; const numbers = Array.isArray(draw.numeros_sorteados) ? draw.numeros_sorteados.map(Number) : []; if (!numbers.includes(number)) numbers.push(number); try { await updateTable('sorteios', { numeros_sorteados: numbers, ultimo_numero: number, status: draw.status === 'aguardando' ? 'em_andamento' : draw.status }, draw.id); $('#called-number').value = ''; feedback('#draw-feedback', 'Número atualizado ao vivo.'); } catch (error) { feedback('#draw-feedback', error.message, true); } }
  if (event.target.id === 'alert-form') { event.preventDefault(); const message = $('#alert-message').value.trim(); if (!message) return; if (state.alertStatus !== 'SUBSCRIBED') { feedback('#alert-feedback', 'Canal de avisos ainda conectando. Aguarde alguns segundos e tente de novo.', true); return; } const result = await state.alertChannel.send({ type: 'broadcast', event: 'alerta', payload: { mensagem: message } }); if (result === 'ok') { feedback('#alert-feedback', 'Alerta enviado para os visitantes conectados.'); $('#alert-message').value = ''; } else feedback('#alert-feedback', 'Não foi possível enviar o alerta. Tente novamente.', true); }
});
document.addEventListener('click', async (event) => { if (event.target.id === 'reset-draw') { const draw = state.sorteios.find((item) => String(item.id) === $('#active-draw').value); if (!draw || !window.confirm('Limpar todos os números deste sorteio?')) return; try { await updateTable('sorteios', { numeros_sorteados: [], ultimo_numero: null, status: 'aguardando' }, draw.id); feedback('#draw-feedback', 'Sorteio resetado.'); } catch (error) { feedback('#draw-feedback', error.message, true); } } });
const { data: { session } } = await supabase.auth.getSession(); if (session) showAdmin(session);
