-- Um mesmo site, várias festas.
--
-- Cada escola vira uma linha em `public.eventos`, identificada por um slug que
-- é o caminho da URL: /casavequia, /raimundo-herminio. Todo o conteúdo passa a
-- pendurar em `evento_id`, então duas festas nunca se misturam, mesmo rodando
-- no mesmo deploy e no mesmo banco.
--
-- A migration é segura em banco que já tem dados: o conteúdo existente é
-- adotado pelo primeiro evento, sem perder nada.

-- 1. Tabela de eventos ---------------------------------------------------------
create table if not exists public.eventos (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nome text not null,
  escola text,
  data_evento date,
  logo_url text,
  pix_chave text,
  pix_favorecido text,
  pix_banco text,
  pix_qr_url text,
  whatsapp text,
  ativo boolean not null default true,
  criado_em timestamptz not null default now()
);

-- O slug vira caminho de URL, então precisa ser minúsculo, sem acento e sem
-- barra. E não pode colidir com arquivo do site: a Vercel resolve o sistema de
-- arquivos ANTES do rewrite, e um evento chamado "admin" ficaria inacessível.
alter table public.eventos drop constraint if exists eventos_slug_formato_check;
alter table public.eventos add constraint eventos_slug_formato_check
  check (slug ~ '^[a-z0-9][a-z0-9-]{1,40}$');

alter table public.eventos drop constraint if exists eventos_slug_reservado_check;
alter table public.eventos add constraint eventos_slug_reservado_check
  check (slug not in (
    'admin', 'assets', 'js', 'api', 'app', 'index', 'style', 'static',
    'favicon', 'robots', 'sitemap', 'public', 'supabase', 'well-known'
  ));

comment on table public.eventos is
  'Uma festa por linha. O slug é o caminho da URL pública: /casavequia.';

-- 2. Vínculo do conteúdo com o evento -----------------------------------------
alter table public.produtos    add column if not exists evento_id bigint references public.eventos (id) on delete cascade;
alter table public.sorteios    add column if not exists evento_id bigint references public.eventos (id) on delete cascade;
alter table public.cronograma  add column if not exists evento_id bigint references public.eventos (id) on delete cascade;
alter table public.candidatas  add column if not exists evento_id bigint references public.eventos (id) on delete cascade;
alter table public.avisos      add column if not exists evento_id bigint references public.eventos (id) on delete cascade;

-- 3. Adoção do conteúdo que já existe ------------------------------------------
do $$
declare
  evento_padrao bigint;
begin
  insert into public.eventos (slug, nome, escola)
  values ('casavequia', 'Festa Cultural', 'Escola Casa Vequia')
  on conflict (slug) do nothing;

  select id into evento_padrao from public.eventos where slug = 'casavequia';

  update public.produtos   set evento_id = evento_padrao where evento_id is null;
  update public.sorteios   set evento_id = evento_padrao where evento_id is null;
  update public.cronograma set evento_id = evento_padrao where evento_id is null;
  update public.candidatas set evento_id = evento_padrao where evento_id is null;
  update public.avisos     set evento_id = evento_padrao where evento_id is null;

  -- A segunda escola já entra cadastrada, ainda sem conteúdo.
  insert into public.eventos (slug, nome, escola)
  values ('raimundo-herminio', 'Festa Cultural', 'Escola Raimundo Hermínio')
  on conflict (slug) do nothing;
end;
$$;

-- Agora que ninguém está órfão, o vínculo passa a ser obrigatório.
alter table public.produtos   alter column evento_id set not null;
alter table public.sorteios   alter column evento_id set not null;
alter table public.cronograma alter column evento_id set not null;
alter table public.candidatas alter column evento_id set not null;
alter table public.avisos     alter column evento_id set not null;

create index if not exists produtos_evento_idx   on public.produtos (evento_id);
create index if not exists sorteios_evento_idx   on public.sorteios (evento_id);
create index if not exists cronograma_evento_idx on public.cronograma (evento_id);
create index if not exists candidatas_evento_idx on public.candidatas (evento_id);
create index if not exists avisos_evento_idx     on public.avisos (evento_id, id desc);

-- 4. Acesso --------------------------------------------------------------------
alter table public.eventos enable row level security;

grant select on public.eventos to anon, authenticated;
grant insert, update, delete on public.eventos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Leitura pública: eventos" on public.eventos;
drop policy if exists "Escrita restrita a organizadores: eventos" on public.eventos;

-- Visitante lê a lista para escolher a festa e para carregar a marca da dele.
create policy "Leitura pública: eventos"
  on public.eventos for select to anon, authenticated using (true);

create policy "Escrita restrita a organizadores: eventos"
  on public.eventos for all to authenticated
  using ((select private.is_organizador()))
  with check ((select private.is_organizador()));

-- 5. Realtime ------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'eventos'
  ) then
    execute 'alter publication supabase_realtime add table public.eventos';
  end if;
end;
$$;

alter table public.eventos replica identity full;
