-- Página da equipe da escola: fardas e contribuição.
--
-- Contexto: além da festa que o público vê, a escola tem um planejamento
-- interno — escolher o modelo da farda, cada um informar tamanho e nome nas
-- costas, e acompanhar quem já pagou a contribuição. Isso circulava por grupo
-- de WhatsApp e planilha solta. Agora mora em /<festa>/funcionarios.
--
-- Identificação: o funcionário NÃO tem conta. Ele se identifica pelo nome
-- completo e recebe um token opaco, guardado no próprio celular; é esse token
-- que autoriza o voto dele e a farda dele. O token fica em `private`, fora da
-- API, senão qualquer um leria a lista de tokens e agiria pelos colegas.
--
-- Por isso toda escrita do funcionário passa por função SECURITY DEFINER: nas
-- tabelas ele não tem grant nenhum de escrita. Marcar "pago" continua sendo
-- exclusividade do organizador, como no resto do painel.

-- 1. Modelos de farda ---------------------------------------------------------
create table if not exists public.farda_modelos (
  id bigint generated by default as identity primary key,
  evento_id bigint not null references public.eventos (id) on delete cascade,
  nome text not null check (length(btrim(nome)) between 1 and 60),
  descricao text,
  imagem_url text,
  criado_em timestamptz not null default now()
);

create index if not exists farda_modelos_evento_idx on public.farda_modelos (evento_id);

comment on table public.farda_modelos is
  'Modelos de farda que a equipe vota. A organização cadastra um por foto.';

-- 2. Funcionários -------------------------------------------------------------
create table if not exists public.funcionarios (
  id bigint generated by default as identity primary key,
  evento_id bigint not null references public.eventos (id) on delete cascade,
  nome text not null check (length(btrim(nome)) between 3 and 90),
  cargo text not null default 'apoio'
    check (cargo in ('gestao', 'professores', 'aee', 'administrativo', 'transporte', 'apoio')),
  contribuicao_valor numeric(10, 2) check (contribuicao_valor is null or contribuicao_valor >= 0),
  contribuicao_paga boolean not null default false,
  farda_nome text,
  farda_gola text check (farda_gola is null or farda_gola in ('polo', 't-shirt')),
  farda_corte text check (farda_corte is null or farda_corte in ('masculino', 'feminino')),
  farda_tamanho text check (farda_tamanho is null or farda_tamanho in ('P', 'M', 'G', 'GG')),
  farda_baby_look boolean,
  farda_preenchida_em timestamptz,
  farda_paga boolean not null default false,
  criado_em timestamptz not null default now()
);

-- Um nome por festa: é o que permite a pessoa voltar pelo mesmo nome de outro
-- aparelho e reencontrar o próprio cadastro, em vez de duplicar a lista.
create unique index if not exists funcionarios_nome_unico on public.funcionarios (evento_id, lower(nome));
create index if not exists funcionarios_evento_idx on public.funcionarios (evento_id);

-- "Apenas um nome e uma inicial": Maria, Maria S. ou Maria S — nunca o nome
-- completo, que não cabe nas costas da camisa.
alter table public.funcionarios drop constraint if exists funcionarios_farda_nome_check;
alter table public.funcionarios add constraint funcionarios_farda_nome_check
  check (farda_nome is null or farda_nome ~ '^[[:alpha:]''.-]{2,20}( [[:alpha:]]\.?)?$');

comment on column public.funcionarios.farda_nome is
  'Nome estampado nas costas: um nome e, no máximo, uma inicial.';
comment on column public.funcionarios.contribuicao_paga is
  'Só a organização muda. O funcionário enxerga, mas não altera.';

-- 3. Token de acesso, fora da API ---------------------------------------------
-- Em `public` esta coluna seria lida por qualquer um com a chave anon, e quem
-- lesse o token de um colega passaria a votar e pedir farda no lugar dele.
create table if not exists private.funcionario_acesso (
  funcionario_id bigint primary key references public.funcionarios (id) on delete cascade,
  token uuid not null unique default gen_random_uuid(),
  criado_em timestamptz not null default now()
);

alter table private.funcionario_acesso enable row level security;
-- Sem policies de propósito: nenhum papel da API alcança esta tabela.

comment on table private.funcionario_acesso is
  'Token opaco que identifica o funcionário no celular dele. Nunca sai por SELECT: só as funções desta migration o consultam.';

-- 4. Votos --------------------------------------------------------------------
create table if not exists public.farda_votos (
  id bigint generated by default as identity primary key,
  evento_id bigint not null references public.eventos (id) on delete cascade,
  modelo_id bigint not null references public.farda_modelos (id) on delete cascade,
  funcionario_id bigint not null unique references public.funcionarios (id) on delete cascade,
  criado_em timestamptz not null default now()
);

create index if not exists farda_votos_modelo_idx on public.farda_votos (modelo_id);
create index if not exists farda_votos_evento_idx on public.farda_votos (evento_id);

comment on table public.farda_votos is
  'Um voto por funcionário. Trocar de modelo atualiza a mesma linha.';

-- 5. Senha da equipe, em tabela separada --------------------------------------
-- Não pode virar coluna de `public.eventos`: aquela tabela é lida pelo site
-- público com `select *`, e a senha sairia junto na resposta.
create table if not exists public.equipe_acesso (
  evento_id bigint primary key references public.eventos (id) on delete cascade,
  codigo text,
  atualizado_em timestamptz not null default now()
);

comment on table public.equipe_acesso is
  'Senha única que a equipe digita para abrir /<festa>/funcionarios. Vazia = qualquer pessoa com o endereço entra.';

alter table public.equipe_acesso enable row level security;

-- anon não recebe grant nenhum aqui: a página descobre se há senha pela
-- função equipe_exige_codigo(), que devolve só um sim ou não.
grant select, insert, update, delete on public.equipe_acesso to authenticated;

drop policy if exists "Escrita restrita a organizadores: equipe_acesso" on public.equipe_acesso;
create policy "Escrita restrita a organizadores: equipe_acesso"
  on public.equipe_acesso for all to authenticated
  using ((select private.is_organizador())) with check ((select private.is_organizador()));

-- 6. Configuração da página, na festa -----------------------------------------
alter table public.eventos
  add column if not exists farda_votacao_ate date,
  add column if not exists farda_pagamento_ate date,
  add column if not exists farda_medidas text,
  add column if not exists farda_modelo_id bigint,
  add column if not exists contribuicao_ate date,
  add column if not exists contribuicao_texto text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'eventos_farda_modelo_id_fkey') then
    alter table public.eventos
      add constraint eventos_farda_modelo_id_fkey
      foreign key (farda_modelo_id) references public.farda_modelos (id) on delete set null;
  end if;
end;
$$;

comment on column public.eventos.farda_votacao_ate is
  'Último dia de votação do modelo. Fecha à meia-noite (horário de Brasília) deste dia.';
comment on column public.eventos.farda_medidas is
  'Tabela de medidas, uma linha por tamanho: "P | 50 | 70" (tamanho | largura cm | altura cm).';
comment on column public.eventos.farda_modelo_id is
  'Modelo definido pela organização. Vazio = vale o mais votado depois do prazo.';

-- O endereço /<festa>/funcionarios é servido por um arquivo do site, então
-- nenhuma festa pode se chamar "funcionarios" — a Vercel resolve o arquivo
-- antes do rewrite e a festa ficaria inalcançável.
alter table public.eventos drop constraint if exists eventos_slug_reservado_check;
alter table public.eventos add constraint eventos_slug_reservado_check
  check (slug not in (
    'admin', 'assets', 'js', 'api', 'app', 'index', 'style', 'static',
    'favicon', 'robots', 'sitemap', 'public', 'supabase', 'well-known',
    'funcionarios'
  ));

-- 7. Acesso -------------------------------------------------------------------
alter table public.farda_modelos enable row level security;
alter table public.funcionarios  enable row level security;
alter table public.farda_votos   enable row level security;

-- Leitura aberta: a página é anônima e precisa montar a grade de modelos, os
-- contadores de voto e as duas listas. Escrita, nenhuma para anon — o
-- funcionário escreve só pelas funções da seção 8.
grant select on public.farda_modelos, public.funcionarios, public.farda_votos to anon, authenticated;
grant insert, update, delete on public.farda_modelos, public.funcionarios, public.farda_votos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Leitura pública: farda_modelos" on public.farda_modelos;
drop policy if exists "Leitura pública: funcionarios" on public.funcionarios;
drop policy if exists "Leitura pública: farda_votos" on public.farda_votos;
drop policy if exists "Escrita restrita a organizadores: farda_modelos" on public.farda_modelos;
drop policy if exists "Escrita restrita a organizadores: funcionarios" on public.funcionarios;
drop policy if exists "Escrita restrita a organizadores: farda_votos" on public.farda_votos;

create policy "Leitura pública: farda_modelos"
  on public.farda_modelos for select to anon, authenticated using (true);
create policy "Leitura pública: funcionarios"
  on public.funcionarios for select to anon, authenticated using (true);
create policy "Leitura pública: farda_votos"
  on public.farda_votos for select to anon, authenticated using (true);

create policy "Escrita restrita a organizadores: farda_modelos"
  on public.farda_modelos for all to authenticated
  using ((select private.is_organizador())) with check ((select private.is_organizador()));
create policy "Escrita restrita a organizadores: funcionarios"
  on public.funcionarios for all to authenticated
  using ((select private.is_organizador())) with check ((select private.is_organizador()));
create policy "Escrita restrita a organizadores: farda_votos"
  on public.farda_votos for all to authenticated
  using ((select private.is_organizador())) with check ((select private.is_organizador()));

-- 8. O que o funcionário pode fazer -------------------------------------------
-- O prazo é o ÚLTIMO dia válido, e o corte usa o fuso de Brasília para a
-- votação não fechar às 21h por causa do UTC.
create or replace function public.prazo_encerrado(p_data date)
returns boolean
language sql
stable
set search_path = ''
as $$
  select p_data is not null and (now() at time zone 'America/Sao_Paulo')::date > p_data;
$$;

comment on function public.prazo_encerrado(date) is
  'Verdadeiro depois de passado o dia informado, no horário de Brasília.';

-- Só um sim ou não: é o suficiente para a página decidir se mostra o campo de
-- senha, e não revela a senha em si.
create or replace function public.equipe_exige_codigo(p_slug text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.equipe_acesso a
    join public.eventos e on e.id = a.evento_id
    where e.slug = lower(btrim(coalesce(p_slug, '')))
      and coalesce(btrim(a.codigo), '') <> ''
  );
$$;

-- Entrar: cria o cadastro no primeiro acesso, ou devolve o token de quem já
-- está na lista. Com token em mãos, a mesma chamada corrige nome e setor.
create or replace function public.funcionario_entrar(
  p_slug text,
  p_nome text,
  p_cargo text,
  p_codigo text default null,
  p_token uuid default null
)
returns table (id bigint, token uuid, nome text, cargo text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_evento_id bigint;
  v_codigo text;
  v_nome text;
  v_id bigint;
  v_token uuid;
begin
  select e.id into v_evento_id from public.eventos e where e.slug = lower(btrim(coalesce(p_slug, '')));
  if v_evento_id is null then
    raise exception 'Esta festa não existe.' using errcode = 'P0001';
  end if;

  select btrim(coalesce(a.codigo, '')) into v_codigo
  from public.equipe_acesso a where a.evento_id = v_evento_id;

  if coalesce(v_codigo, '') <> '' and lower(btrim(coalesce(p_codigo, ''))) <> lower(v_codigo) then
    raise exception 'Código de acesso incorreto. Peça o código à organização.' using errcode = 'P0001';
  end if;

  -- Espaço duplicado faria "Maria  Silva" virar uma segunda pessoa na lista.
  v_nome := btrim(regexp_replace(coalesce(p_nome, ''), '\s+', ' ', 'g'));
  if length(v_nome) < 5 or position(' ' in v_nome) = 0 then
    raise exception 'Escreva o seu nome completo, com sobrenome.' using errcode = 'P0001';
  end if;

  if p_cargo is null or p_cargo not in ('gestao', 'professores', 'aee', 'administrativo', 'transporte', 'apoio') then
    raise exception 'Escolha o seu setor na escola.' using errcode = 'P0001';
  end if;

  if p_token is not null then
    select a.funcionario_id into v_id
    from private.funcionario_acesso a
    join public.funcionarios f on f.id = a.funcionario_id
    where a.token = p_token and f.evento_id = v_evento_id;
  end if;

  if v_id is null then
    select f.id into v_id from public.funcionarios f
    where f.evento_id = v_evento_id and lower(f.nome) = lower(v_nome);
  end if;

  if v_id is null then
    insert into public.funcionarios (evento_id, nome, cargo)
    values (v_evento_id, v_nome, p_cargo)
    returning public.funcionarios.id into v_id;
  else
    update public.funcionarios f set nome = v_nome, cargo = p_cargo where f.id = v_id;
  end if;

  insert into private.funcionario_acesso (funcionario_id) values (v_id)
  on conflict (funcionario_id) do nothing;

  select a.token into v_token from private.funcionario_acesso a where a.funcionario_id = v_id;
  return query
    select f.id, v_token, f.nome, f.cargo from public.funcionarios f where f.id = v_id;
end;
$$;

-- Votar no modelo. Um voto por pessoa; votar de novo troca o voto.
create or replace function public.funcionario_votar(p_token uuid, p_modelo_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_funcionario public.funcionarios%rowtype;
  v_encerrada boolean;
begin
  select f.* into v_funcionario
  from public.funcionarios f
  join private.funcionario_acesso a on a.funcionario_id = f.id
  where a.token = p_token;
  if not found then
    raise exception 'Identifique-se de novo para votar.' using errcode = 'P0001';
  end if;

  select public.prazo_encerrado(e.farda_votacao_ate) into v_encerrada
  from public.eventos e where e.id = v_funcionario.evento_id;
  if v_encerrada then
    raise exception 'A votação do modelo já foi encerrada.' using errcode = 'P0001';
  end if;

  if not exists (
    select 1 from public.farda_modelos m
    where m.id = p_modelo_id and m.evento_id = v_funcionario.evento_id
  ) then
    raise exception 'Este modelo não está mais disponível.' using errcode = 'P0001';
  end if;

  insert into public.farda_votos (evento_id, modelo_id, funcionario_id)
  values (v_funcionario.evento_id, p_modelo_id, v_funcionario.id)
  on conflict (funcionario_id) do update
    set modelo_id = excluded.modelo_id, criado_em = now();
end;
$$;

-- Informações da farda. Nada aqui toca em `farda_paga`: quem dá baixa no
-- pagamento é a organização, pelo painel.
create or replace function public.funcionario_salvar_farda(
  p_token uuid,
  p_nome text,
  p_gola text,
  p_corte text,
  p_tamanho text,
  p_baby_look boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
begin
  select a.funcionario_id into v_id from private.funcionario_acesso a where a.token = p_token;
  if v_id is null then
    raise exception 'Identifique-se de novo para salvar a sua farda.' using errcode = 'P0001';
  end if;
  if p_gola is null or p_gola not in ('polo', 't-shirt') then
    raise exception 'Escolha entre gola polo e t-shirt.' using errcode = 'P0001';
  end if;
  if p_corte is null or p_corte not in ('masculino', 'feminino') then
    raise exception 'Escolha o modelo masculino ou feminino.' using errcode = 'P0001';
  end if;
  if p_tamanho is null or p_tamanho not in ('P', 'M', 'G', 'GG') then
    raise exception 'Escolha o tamanho da farda.' using errcode = 'P0001';
  end if;

  update public.funcionarios f set
    farda_nome = nullif(btrim(regexp_replace(coalesce(p_nome, ''), '\s+', ' ', 'g')), ''),
    farda_gola = p_gola,
    farda_corte = p_corte,
    farda_tamanho = p_tamanho,
    farda_baby_look = coalesce(p_baby_look, false),
    farda_preenchida_em = now()
  where f.id = v_id;
end;
$$;

grant execute on function public.prazo_encerrado(date) to anon, authenticated;
grant execute on function public.equipe_exige_codigo(text) to anon, authenticated;
grant execute on function public.funcionario_entrar(text, text, text, text, uuid) to anon, authenticated;
grant execute on function public.funcionario_votar(uuid, bigint) to anon, authenticated;
grant execute on function public.funcionario_salvar_farda(uuid, text, text, text, text, boolean) to anon, authenticated;

-- 9. Realtime -----------------------------------------------------------------
do $$
declare
  tabela text;
begin
  foreach tabela in array array['farda_modelos', 'funcionarios', 'farda_votos']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = tabela
    ) then
      execute format('alter publication supabase_realtime add table public.%I', tabela);
    end if;
    execute format('alter table public.%I replica identity full', tabela);
  end loop;
end;
$$;
