-- Correções de sincronia em tempo real.
--
-- Três problemas encontrados em teste (organizador no PC, visitante no celular):
--
-- 1. Escrita silenciosa. Um UPDATE bloqueado pelo RLS casa ZERO linhas e o
--    PostgREST responde 204 sem erro. O painel dizia "salvo" e o banco não
--    mudava — logo, nada chegava ao visitante. O painel agora confere quantas
--    linhas voltaram, mas ele também precisa conseguir DIZER ao organizador
--    que ele está fora da allowlist: daí a função pública abaixo.
--
-- 2. O aviso global dependia de um broadcast em canal privado. `send()` devolve
--    'ok' assim que a mensagem sai do navegador, mesmo quando o servidor a
--    descarta por falta de permissão — e quem abrisse o site depois do disparo
--    nunca veria o recado. Agora o aviso é uma linha em `public.avisos`:
--    leitura pública, escrita restrita, e chega pelo mesmo Postgres Changes
--    que o resto do site.
--
-- 3. Sem REPLICA IDENTITY FULL, os eventos de UPDATE/DELETE chegam ao Realtime
--    sem o registro completo, e a checagem de RLS que ele faz por assinante
--    pode descartá-los. Em tabelas pequenas como estas o custo em WAL é
--    irrelevante perto de perder atualização na hora da festa.

-- 1. Checagem de permissão visível para o painel -------------------------------
-- `private.is_organizador()` não é alcançável pela API (o PostgREST só expõe
-- `public`). Este wrapper responde apenas sobre quem está chamando.
create or replace function public.sou_organizador()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.is_organizador();
$$;

revoke execute on function public.sou_organizador() from public, anon;
grant execute on function public.sou_organizador() to authenticated;

comment on function public.sou_organizador() is
  'Permite ao painel avisar o organizador quando a conta dele está fora da allowlist, em vez de falhar em silêncio.';

-- 2. Avisos globais como tabela ------------------------------------------------
create table if not exists public.avisos (
  id bigint generated by default as identity primary key,
  mensagem text not null check (length(btrim(mensagem)) between 1 and 240),
  criado_em timestamptz not null default now()
);

create index if not exists avisos_criado_em_idx on public.avisos (criado_em desc);

alter table public.avisos enable row level security;

grant select on public.avisos to anon, authenticated;
grant insert, delete on public.avisos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Leitura pública: avisos" on public.avisos;
drop policy if exists "Escrita restrita a organizadores: avisos" on public.avisos;

create policy "Leitura pública: avisos"
  on public.avisos for select to anon, authenticated using (true);

create policy "Escrita restrita a organizadores: avisos"
  on public.avisos for all to authenticated
  using ((select private.is_organizador()))
  with check ((select private.is_organizador()));

-- 3. Publicação e identidade de réplica ---------------------------------------
do $$
declare
  tabela text;
begin
  foreach tabela in array array['produtos', 'sorteios', 'cronograma', 'candidatas', 'avisos']
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = tabela
    ) then
      execute format('alter publication supabase_realtime add table public.%I', tabela);
    end if;

    execute format('alter table public.%I replica identity full', tabela);
  end loop;
end;
$$;
