-- Festa Cultural: esquema inicial, políticas de acesso e Postgres Changes.
-- A chave service_role nunca deve ser usada pelo navegador.

create table public.produtos (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nome text not null,
  descricao text,
  preco numeric(10, 2) not null default 0 check (preco >= 0),
  imagem_url text,
  categoria text not null check (categoria in ('comida', 'salgado', 'doce', 'bebida', 'brincadeira')),
  status text not null default 'disponivel' check (status in ('disponivel', 'poucas_unidades', 'esgotado')),
  limite_alerta integer check (limite_alerta is null or limite_alerta >= 0)
);

create table public.sorteios (
  id bigint generated by default as identity primary key,
  identificacao text not null,
  premio text not null,
  tipo text not null check (tipo in ('bingo', 'rifa', 'leilao')),
  valor_cartela numeric(10, 2) not null default 0 check (valor_cartela >= 0),
  status text not null default 'aguardando' check (status in ('aguardando', 'em_andamento', 'realizado')),
  numeros_sorteados jsonb not null default '[]'::jsonb check (jsonb_typeof(numeros_sorteados) = 'array'),
  ultimo_numero integer
);

create table public.cronograma (
  id bigint generated by default as identity primary key,
  evento text not null,
  horario_previsto time not null,
  status text not null default 'pendente' check (status in ('pendente', 'realizado')),
  sorteio_id bigint references public.sorteios(id) on delete set null
);

create table public.candidatas (
  id bigint generated by default as identity primary key,
  nome text not null,
  detalhes text,
  foto_url text,
  horario_desfile time
);

create index produtos_categoria_idx on public.produtos (categoria);
create index produtos_status_idx on public.produtos (status);
create index sorteios_status_idx on public.sorteios (status);
create index cronograma_horario_previsto_idx on public.cronograma (horario_previsto);

alter table public.produtos enable row level security;
alter table public.sorteios enable row level security;
alter table public.cronograma enable row level security;
alter table public.candidatas enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.produtos, public.sorteios, public.cronograma, public.candidatas to anon, authenticated;
grant insert, update, delete on public.produtos, public.sorteios, public.cronograma, public.candidatas to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create policy "Leitura pública: produtos"
  on public.produtos for select to anon, authenticated using (true);
create policy "Leitura pública: sorteios"
  on public.sorteios for select to anon, authenticated using (true);
create policy "Leitura pública: cronograma"
  on public.cronograma for select to anon, authenticated using (true);
create policy "Leitura pública: candidatas"
  on public.candidatas for select to anon, authenticated using (true);

-- O painel não expõe cadastro: usuários autenticados são os organizadores.
-- Se o projeto futuramente possuir usuários visitantes autenticados, substitua
-- estas políticas por uma verificação de função/claim administrativo.
create policy "Organizadores autenticados: produtos"
  on public.produtos for all to authenticated using (true) with check (true);
create policy "Organizadores autenticados: sorteios"
  on public.sorteios for all to authenticated using (true) with check (true);
create policy "Organizadores autenticados: cronograma"
  on public.cronograma for all to authenticated using (true) with check (true);
create policy "Organizadores autenticados: candidatas"
  on public.candidatas for all to authenticated using (true) with check (true);

do $$
declare
  tabela text;
begin
  foreach tabela in array array['produtos', 'sorteios', 'cronograma', 'candidatas']
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = tabela
    ) then
      execute format('alter publication supabase_realtime add table public.%I', tabela);
    end if;
  end loop;
end;
$$;
