-- Tecidos da farda e a grade de tamanhos por gênero.
--
-- Contexto: escolher a farda era só gola, corte e um tamanho P/M/G/GG. Faltavam
-- as duas coisas que a pessoa realmente precisa saber antes de decidir — de que
-- malha é a camisa (e quanto ela custa) e qual tamanho serve nela.
--
-- Os tecidos são catálogo do fornecedor, iguais em toda escola: vêm semeados
-- aqui e toda festa nova nasce com os quatro. A organização edita preço, foto e
-- texto, ou apaga o que não vender.
--
-- A grade de medidas deixa de ser texto solto em `eventos.farda_medidas` e vira
-- tabela fixa no front-end, porque é a grade da confecção, não de cada festa.

-- 1. Catálogo de tecidos ------------------------------------------------------
create table if not exists public.farda_tecidos (
  id bigint generated by default as identity primary key,
  evento_id bigint not null references public.eventos (id) on delete cascade,
  nome text not null check (length(btrim(nome)) between 1 and 60),
  preco numeric(10, 2) not null default 0 check (preco >= 0),
  resumo text,
  descricao text,
  caracteristicas text,
  imagem_url text,
  ordem smallint not null default 10,
  criado_em timestamptz not null default now()
);

create index if not exists farda_tecidos_evento_idx on public.farda_tecidos (evento_id, ordem, id);

comment on table public.farda_tecidos is
  'Malhas disponíveis para a farda, com o preço de cada uma. Catálogo do fornecedor, semeado por festa.';
comment on column public.farda_tecidos.resumo is
  'Uma linha embaixo do nome no card de escolha.';
comment on column public.farda_tecidos.descricao is
  'Texto completo, exibido só quando a pessoa abre os detalhes do tecido.';
comment on column public.farda_tecidos.caracteristicas is
  'Uma característica por linha. Ex.: "Secagem rápida".';

-- 2. Escolha da pessoa --------------------------------------------------------
alter table public.funcionarios
  add column if not exists farda_tecido_id bigint references public.farda_tecidos (id) on delete set null;

comment on column public.funcionarios.farda_tecido_id is
  'Tecido escolhido. O preço a cobrar é o do tecido no momento do pedido.';

-- 3. Grade de tamanhos --------------------------------------------------------
-- A grade feminina é a baby look da confecção: PPBL a XGGBL. A masculina vai de
-- PP a XGG. Os dois conjuntos são distintos de propósito — é o sufixo BL que
-- diz à confecção qual molde usar.
alter table public.funcionarios drop constraint if exists funcionarios_farda_tamanho_check;
alter table public.funcionarios add constraint funcionarios_farda_tamanho_check
  check (farda_tamanho is null or farda_tamanho in (
    'PP', 'P', 'M', 'G', 'GG', 'XG', 'XGG',
    'PPBL', 'PBL', 'MBL', 'GBL', 'GGBL', 'XGBL', 'XGGBL'
  ));

-- Tamanho e gênero não podem se contradizer: "feminino tamanho M" mandaria o
-- molde errado para a confecção.
alter table public.funcionarios drop constraint if exists funcionarios_grade_coerente_check;
alter table public.funcionarios add constraint funcionarios_grade_coerente_check
  check (
    farda_tamanho is null or farda_corte is null
    or (farda_corte = 'feminino') = (farda_tamanho like '%BL')
  );

-- A tabela de medidas por festa deixa de existir: a grade agora é a mesma para
-- todo mundo e mora no front-end.
alter table public.eventos drop column if exists farda_medidas;

-- 3b. Adicionais ---------------------------------------------------------------
-- Gola polo e os três tamanhos maiores custam mais na confecção. Os valores são
-- editáveis por festa; QUAIS tamanhos pagam adicional é regra da grade
-- (GG, XG e XGG, com ou sem o BL) e mora junto da grade, no front-end.
alter table public.eventos
  add column if not exists farda_adicional_polo numeric(10, 2) not null default 10
    check (farda_adicional_polo >= 0),
  add column if not exists farda_adicional_tamanho numeric(10, 2) not null default 8
    check (farda_adicional_tamanho >= 0);

comment on column public.eventos.farda_adicional_polo is
  'Acréscimo cobrado quando a gola é polo. Zero remove o adicional da tela.';
comment on column public.eventos.farda_adicional_tamanho is
  'Acréscimo dos tamanhos GG, XG e XGG (e GGBL, XGBL, XGGBL). Zero remove o adicional da tela.';

-- 4. Acesso -------------------------------------------------------------------
alter table public.farda_tecidos enable row level security;

grant select on public.farda_tecidos to anon, authenticated;
grant insert, update, delete on public.farda_tecidos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Leitura pública: farda_tecidos" on public.farda_tecidos;
drop policy if exists "Escrita restrita a organizadores: farda_tecidos" on public.farda_tecidos;

create policy "Leitura pública: farda_tecidos"
  on public.farda_tecidos for select to anon, authenticated using (true);
create policy "Escrita restrita a organizadores: farda_tecidos"
  on public.farda_tecidos for all to authenticated
  using ((select private.is_organizador())) with check ((select private.is_organizador()));

-- 5. Semeadura do catálogo ----------------------------------------------------
-- As fotos ficam vazias: a organização envia as artes de cada malha pelo painel,
-- que já grava no bucket `festa`. Inventar uma URL aqui daria imagem quebrada.
create or replace function private.semear_tecidos(p_evento_id bigint)
returns void
language sql
set search_path = ''
as $$
  insert into public.farda_tecidos (evento_id, nome, preco, resumo, descricao, caracteristicas, ordem)
  select p_evento_id, t.nome, t.preco, t.resumo, t.descricao, t.caracteristicas, t.ordem
  from (values
    (
      'KX Premium', 50.00, 'Tecido premium',
      'O tecido KX Premium foi desenvolvido para quem busca o equilíbrio perfeito entre elegância, conforto e durabilidade.',
      E'Alta resistência\nDurabilidade superior\nToque macio e confortável\nRespirável\nCores sofisticadas e atemporais',
      10::smallint
    ),
    (
      'KX Sport', 54.00, 'Tecido esportivo premium',
      'O tecido KX Sport foi desenvolvido para máxima performance. Leve, macio e com toque suave, oferece liberdade de movimento, secagem rápida e conforto térmico em todas as atividades.',
      E'Leve e macio ao toque\nSecagem rápida\nRespirável e confortável\nFlexibilidade e liberdade\nAlta resistência e durabilidade\nProteção UV FPS 50+',
      20::smallint
    ),
    (
      'DRY Jackad', 62.00, 'Tecido esportivo premium',
      'O tecido KX Dry Jackad foi desenvolvido para máxima performance. Com textura respirável e tecnologia de secagem rápida, proporciona leveza, conforto térmico e liberdade de movimento em todas as atividades.',
      E'Alta respirabilidade\nSecagem rápida\nLeve e confortável\nFlexibilidade e liberdade\nAlta resistência e durabilidade\nProteção UV FPS 50+',
      30::smallint
    ),
    (
      'PP-Poliéster', 60.00, 'Tecido premium',
      'O tecido KX Poliéster foi desenvolvido para unir leveza, resistência e praticidade. Sua composição em poliéster garante durabilidade, secagem rápida e excelente caimento para o dia a dia.',
      E'Alta resistência\nLeve e confortável\nRespirável\nSecagem rápida\nNão amassa com facilidade\nCores vivas e duradouras',
      40::smallint
    )
  ) as t(nome, preco, resumo, descricao, caracteristicas, ordem)
  -- Reaplicar o script não pode duplicar o catálogo nem desfazer edição da escola.
  where not exists (
    select 1 from public.farda_tecidos existente
    where existente.evento_id = p_evento_id and lower(existente.nome) = lower(t.nome)
  );
$$;

-- Festas que já existem.
do $$
declare
  festa bigint;
begin
  for festa in select id from public.eventos loop
    perform private.semear_tecidos(festa);
  end loop;
end;
$$;

-- E as próximas, sem ninguém precisar redigitar o catálogo.
create or replace function public.semear_tecidos_da_festa()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.semear_tecidos(new.id);
  return new;
end;
$$;

drop trigger if exists eventos_semeia_tecidos on public.eventos;
create trigger eventos_semeia_tecidos
  after insert on public.eventos
  for each row execute function public.semear_tecidos_da_festa();

-- 6. A farda passa a guardar o tecido ----------------------------------------
create or replace function public.funcionario_salvar_farda(
  p_token uuid,
  p_nome text,
  p_gola text,
  p_corte text,
  p_tamanho text,
  p_baby_look boolean,
  p_tecido_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_evento_id bigint;
begin
  select a.funcionario_id, f.evento_id into v_id, v_evento_id
  from private.funcionario_acesso a
  join public.funcionarios f on f.id = a.funcionario_id
  where a.token = p_token;
  if v_id is null then
    raise exception 'Identifique-se de novo para salvar a sua farda.' using errcode = 'P0001';
  end if;
  if p_gola is null or p_gola not in ('polo', 't-shirt') then
    raise exception 'Escolha entre gola polo e t-shirt.' using errcode = 'P0001';
  end if;
  if p_corte is null or p_corte not in ('masculino', 'feminino') then
    raise exception 'Escolha a grade masculina ou feminina.' using errcode = 'P0001';
  end if;
  if p_tamanho is null then
    raise exception 'Escolha o tamanho da farda.' using errcode = 'P0001';
  end if;
  -- O sufixo BL é o que diz à confecção que o molde é baby look.
  if (p_corte = 'feminino') <> (p_tamanho like '%BL') then
    raise exception 'Este tamanho não pertence à grade escolhida.' using errcode = 'P0001';
  end if;
  if p_tecido_id is not null and not exists (
    select 1 from public.farda_tecidos t where t.id = p_tecido_id and t.evento_id = v_evento_id
  ) then
    raise exception 'Este tecido não está mais disponível.' using errcode = 'P0001';
  end if;

  update public.funcionarios f set
    farda_nome = nullif(btrim(regexp_replace(coalesce(p_nome, ''), '\s+', ' ', 'g')), ''),
    farda_gola = p_gola,
    farda_corte = p_corte,
    farda_tamanho = p_tamanho,
    farda_baby_look = coalesce(p_baby_look, false),
    farda_tecido_id = p_tecido_id,
    farda_preenchida_em = now()
  where f.id = v_id;
end;
$$;

-- A assinatura mudou; a antiga sairia respondendo pela nova em chamada sem tecido.
drop function if exists public.funcionario_salvar_farda(uuid, text, text, text, text, boolean);

grant execute on function public.funcionario_salvar_farda(uuid, text, text, text, text, boolean, bigint) to anon, authenticated;

-- 7. Realtime -----------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'farda_tecidos'
  ) then
    execute 'alter publication supabase_realtime add table public.farda_tecidos';
  end if;
end;
$$;

alter table public.farda_tecidos replica identity full;
